image: node:latest
before_script:
  - npm install
cache:
  key: ${CI_COMMIT_REF_SLUG}

build:
  script:
    - NODE_ENV=production npm run build

audit:
  allow_failure: true
  script:
    - npm audit

eslint:
  script:
    - npx eslint src
